export type Ville = {
  slug: string
  nom: string
  tier: 1 | 2 | 3
  quartiers: string
  climat: string
  habitat: string
}

export const villes: Ville[] = [
  { slug: "nice", nom: "Nice", tier: 1,
    quartiers: "Vieux Nice, Promenade des Anglais, Magnan, Saint-Roch, Cimiez",
    climat: "Nice connaît des étés chauds et secs et des hivers doux typiques du climat méditerranéen. La climatisation réversible et l'isolation des combles y sont particulièrement rentables, réduisant à la fois les besoins de chauffage hivernal et de rafraîchissement estival.",
    habitat: "Immeubles haussmanniens du centre-ville, villas des collines, résidences en bord de mer : Nice regroupe une grande diversité de bâti, ce qui rend l'audit énergétique préalable indispensable pour cibler les travaux les plus rentables selon votre logement." },
  { slug: "cannes", nom: "Cannes", tier: 1,
    quartiers: "La Croisette, Le Cannet, La Bocca, Le Suquet",
    climat: "Entre la Croisette et les hauteurs du Cannet, le climat cannois reste doux toute l'année. L'isolation des murs par l'extérieur y est particulièrement adaptée, protégeant aussi les façades des embruns marins fréquents en bord de mer.",
    habitat: "Villas de prestige, résidences de standing et immeubles anciens du Suquet : à Cannes, l'isolation thermique par l'extérieur permet souvent de combiner gain énergétique et rénovation esthétique de la façade." },
  { slug: "antibes", nom: "Antibes", tier: 1,
    quartiers: "Vieille Ville, Cap d'Antibes, Golfe-Juan, Juan-les-Pins",
    climat: "Antibes bénéficie d'un climat méditerranéen doux, climat: "Antibes bénéficie d'un climat méditerranéen doux. Une bonne isolation thermique permet d'y limiter efficacement les besoins de chauffage hivernal comme de rafraîchissement estival.",qui assurent à la fois chauffage hivernal et climatisation estivale avec une consommation électrique maîtrisée.",
    habitat: "Le contraste entre les maisons anciennes du centre historique et les villas du Cap d'Antibes appelle des solutions différentes : isolation par l'intérieur pour préserver le cachet ancien, par l'extérieur pour les constructions plus récentes." },
  { slug: "grasse", nom: "Grasse", tier: 1,
    quartiers: "Centre-ville historique, Châteauneuf, Saint-Jacques, Plascassier",
    climat: "Située en altitude au pied des Préalpes, Grasse connaît des nuits sensiblement plus fraîches que le littoral. L'isolation thermique y est encore plus rentable que sur la côte pour réduire les besoins de chauffage hivernal.",
    habitat: "Grasse mélange maisons de parfumeurs anciennes, villas et constructions plus récentes en périphérie, avec des besoins d'isolation variés selon l'altitude et l'exposition de chaque quartier." },
  { slug: "menton", nom: "Menton", tier: 1,
    quartiers: "Vieille Ville, Garavan, Carnolès, Borrigo",
    climat: "Menton bénéficie du micro-climat le plus doux de toute la Côte d'Azur, abrité par les montagnes environnantes. climat: "Menton bénéficie du micro-climat le plus doux de toute la Côte d'Azur, abrité par les montagnes environnantes. Cette douceur permet de limiter fortement les besoins énergétiques d'un logement correctement isolé.", fonctionnant dans des conditions optimales toute l'année.",
    habitat: "Entre la vieille ville aux ruelles étroites et les villas de Garavan, Menton offre une grande variété de configurations qui bénéficient toutes d'un diagnostic énergétique personnalisé." },
  { slug: "cagnes-sur-mer", nom: "Cagnes-sur-Mer", tier: 1,
    quartiers: "Cros-de-Cagnes, Le Haut-de-Cagnes, La Cagne, Les Hauts de Cagnes",
    climat: "Entre le bord de mer du Cros-de-Cagnes et le village perché du Haut-de-Cagnes, les besoins d'isolation varient fortement selon l'exposition et l'altitude du logement.",
    habitat: "Cagnes-sur-Mer regroupe pavillons individuels, résidences récentes et maisons de village anciennes, justifiant un audit énergétique préalable pour prioriser les travaux les plus rentables." },
  { slug: "frejus", nom: "Fréjus", tier: 1,
    quartiers: "Vieille Ville, Port-Fréjus, Fréjus-Plage, Saint-Aygulf",
    climat: "Fréjus profite d'un ensoleillement généreux toute l'année, propice à l'installation de panneaux solaires en complément d'une isolation thermique performante.",
    habitat: "Entre maisons de ville historiques et pavillons des années 1970-1980 très présents dans l'agglomération, l'isolation des combles reste le geste le plus rentable pour réduire rapidement la facture énergétique." },
  { slug: "saint-raphael", nom: "Saint-Raphaël", tier: 2,
    quartiers: "Centre-ville, Valescure, Boulouris, Agay",
    climat: "Saint-Raphaël bénéficie d'un excellent ensoleillement, idéal pour combiner isolation thermique performante et panneaux solaires afin de maximiser les économies d'énergie.",
    habitat: "Villas dans la pinède de Valescure, résidences en bord de mer à Agay : chaque secteur de Saint-Raphaël a ses propres contraintes d'isolation que notre équipe évalue lors de la visite technique." },
  { slug: "mandelieu-la-napoule", nom: "Mandelieu-la-Napoule", tier: 2,
    quartiers: "La Napoule, Mandelieu Centre, Le Capitou",
    climat: "Entre golfs et bord de mer, Mandelieu-la-Napoule bénéficie d'un climat doux toute l'année climat: "Entre golfs et bord de mer, Mandelieu-la-Napoule bénéficie d'un climat doux toute l'année, ce qui rend l'isolation thermique particulièrement rentable sur le long terme.",
    habitat: "Les villas de standing de la commune gagnent en confort et en valeur grâce à une isolation par l'extérieur soignée, qui préserve l'esthétique des façades en bord de mer." },
  { slug: "villeneuve-loubet", nom: "Villeneuve-Loubet", tier: 2,
    quartiers: "Villeneuve-Loubet Plage, le Village, bord du Loup",
    climat: "Villeneuve-Loubet bénéficie d'un climat méditerranéen classique, avec des besoins d'isolation qui varient entre le village perché et les résidences de bord de plage.",
    habitat: "Du village médiéval aux résidences modernes de Marina Baie des Anges, Villeneuve-Loubet regroupe un habitat varié pour lequel un audit énergétique personnalisé permet de prioriser les travaux les plus rentables." },
  { slug: "mougins", nom: "Mougins", tier: 2,
    quartiers: "Village ancien, Mouans-Sartoux, Golfs de Mougins, Font de l'Orme",
    climat: "Mougins bénéficie d'un climat doux et verdoyant, légèrement plus frais que le littoral grâce à son altitude modérée.",
    habitat: "Les villas de standing de Mougins bénéficient particulièrement d'une rénovation énergétique globale, qui allie confort thermique et valorisation patrimoniale du bien." },
  { slug: "valbonne", nom: "Valbonne", tier: 2,
    quartiers: "Vieux Valbonne, proximité Sophia-Antipolis, La Bouilladisse",
    climat: "À Valbonne, le climat reste doux mais légèrement plus frais qu'en bord de mer en raison de l'altitude du plateau.",
    habitat: "Entre village provençal authentique et résidences modernes proches de la technopole, l'isolation des combles et des murs reste la priorité numéro un pour réduire les déperditions thermiques." },
  { slug: "sophia-antipolis", nom: "Sophia-Antipolis", tier: 2,
    quartiers: "Les Bouillides, Garbejaire, La Fontonne, technopole",
    climat: "Sophia-Antipolis bénéficie d'un climat méditerranéen tempéré par la végétation environnante du parc technologique.",
    habitat: "Les constructions plus récentes de la technopole profitent grandement habitat: "Les constructions plus récentes de la technopole profitent grandement d'une isolation thermique ciblée pour optimiser leur classe énergétique sans travaux excessifs." }, complémentaire pour optimiser leur classe énergétique." },
  { slug: "biot", nom: "Biot", tier: 3,
    quartiers: "Village ancien, Biot-Plage, La Brague",
    climat: "Le village perché de Biot bénéficie d'un climat méditerranéen classique, avec une légère fraîcheur nocturne due à l'altitude du village historique.",
    habitat: "Le bâti ancien du village de Biot bénéficie d'une isolation par l'intérieur, plus respectueuse du cachet architectural et plus simple à mettre en œuvre dans des ruelles étroites." },
  { slug: "vence", nom: "Vence", tier: 3,
    quartiers: "Vieille Ville, Saint-Jeannet, plateau de Vence, Les Baous",
    climat: "En altitude sur son plateau, Vence connaît des hivers nettement plus frais que le littoral. L'isolation des combles y représente un investissement particulièrement rentable.",
    habitat: "Maisons de village en pierre et constructions plus récentes coexistent à Vence, chacune avec des besoins d'isolation spécifiques évalués lors de notre audit énergétique gratuit." },
  { slug: "vallauris", nom: "Vallauris", tier: 3,
    quartiers: "Centre-ville, Golfe-Juan, Le Plan",
    climat: "Vallauris bénéficie d'un climat méditerranéen classique avec une bonne exposition au soleil toute l'année.",
    habitat: "Les maisons individuelles des années 1960-1980, très présentes à Vallauris, sont le profil type idéal pour une rénovation énergétique complète avec aides maximales de l'État." },
  { slug: "saint-laurent-du-var", nom: "Saint-Laurent-du-Var", tier: 3,
    quartiers: "Bord de mer, Cap 3000, Sainte-Marguerite, Saint-Laurent Village",
    climat: "Saint-Laurent-du-Var bénéficie d'une situation littorale exposée aux embruns, un facteur important pour le choix des matériaux d'isolation extérieure.",
    habitat: "Les résidences en bord de mer profitent d'une isolation des murs qui les protège efficacement de l'humidité saline tout en améliorant leur performance thermique." },
  { slug: "roquebrune-cap-martin", nom: "Roquebrune-Cap-Martin", tier: 3,
    quartiers: "Cap-Martin, le village médiéval perché, Carnolès",
    climat: "Entre cap maritime et village perché, Roquebrune-Cap-Martin bénéficie d'un climat très doux toute l'année grâce à sa situation abritée.",
    habitat: "Le contraste entre les villas du Cap-Martin et les maisons du village médiéval perché appelle des solutions d'isolation adaptées à chaque typologie de bâti." },
  { slug: "beausoleil", nom: "Beausoleil", tier: 3,
    quartiers: "Centre-ville, frontière monégasque, Quartier de la Condamine",
    climat: "Beausoleil, à la frontière de Monaco, bénéficie d'un climat très doux protégé par le relief environnant.",
    habitat: "La commune regroupe surtout des immeubles anciens en hauteur, où l'isolation des combles et des parties communes change radicalement le confort thermique des appartements du dernier étage." },
  { slug: "carros", nom: "Carros", tier: 3,
    quartiers: "Carros-Village, Carros-le-Neuf, zone industrielle",
    climat: "Carros, en vallée du Var, connaît des écarts de température plus marqués qu'en bord de mer, avec des hivers plus frais qui justifient une isolation performante.",
    habitat: "Entre village perché historique et zone résidentielle plus récente, Carros profite d'une isolation thermique qui réduit nettement les besoins de chauffage hivernal en vallée du Var." },
]

export function getVille(slug: string) {
  return villes.find(v => v.slug === slug)
}
  

